### PR TITLE
Remove bus and rail node types for now.

### PR DESCRIPTION
**Pull request by dnesbitt61**
fixes issue #200

### CODE REVIEW

**Comment by gknisely** [comment]
will this break anything?

**Comment by dgearhart** [comment]
I was wondering the same thing

**Comment by dnesbitt61** [comment]
These 2 types are not present in code anywhere.  Since the enum has explicit values assigned the enum values do not change (there are now just 2 empty spots). I changed the is_transit method as well to now just check for the MultiUseStop type.

**Comment by dgearhart** [comment]
:shipit:

**Comment by gknisely** [comment]
:train:

**Pull request merged**
