### PR TITLE
added payment.

### PR DESCRIPTION
**Pull request by gknisely**
@dgearhart @dnesbitt61 @kevinkreiser

### CODE REVIEW

**Comment by dnesbitt61** [comment]
Need to have indications of what each bit means. 8 bits is a lot - can we distill into a smaller set?

**Comment by gknisely** [comment]
Is a mask.
// Payment constants. Bit constants.
constexpr uint8_t kCoins  = 1; // Coins
constexpr uint8_t kNotes  = 2; // Bills
constexpr uint8_t kETC    = 4; // Electronic Toll Collector

**Comment by dnesbitt61** [comment]
Added earlier I guess. So you only need 3 bits?

**Comment by gknisely** [comment]
I guess but could be all three...should we add credit cards and other (bitcoin, paypal, etc)

**Pull request closed without merging**
