### PR TITLE
moved StreetName and StreetNames from odin to baldr

### PR DESCRIPTION
**Pull request by dgearhart**
@dnesbitt61 @gknisely @kevinkreiser

### CODE REVIEW

**Comment by dnesbitt61** [comment]
Will this work outside US?

**Comment by dgearhart** [comment]
there is a TODO to implement based on locale

**Comment by dnesbitt61** [comment]
:shipit

**Comment by kevinkreiser** [comment]
is there anyway we could mark this one as the US one and then use it as default until we have a real default?

**Comment by dgearhart** [comment]
I will work on refactor

**Pull request merged**
